<?php

$title = $form->get('title');
$title->setAttribute('class','form-control');

$content = $form->get('content');
$content->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-outline-primary');

$form->setAttribute('action', $this->url('post', ['action'=>'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<style>
    main {
        border: 2px solid white;
        border-radius: 15px;
        padding: 15px;
        max-width: 50%;
        margin: 0 auto;
    }
</style>

<main>

<h1>Adicionar</h1>

    <div class="form-group">
        <?=$this->formLabel($title);?>
        <?=$this->formElement($title);?>
    </div>
    
    <div class="form-group">
        <?=$this->formLabel($content);?>
        <?=$this->formElement($content);?>
    </div>
    
    <?php
        echo $this->formSubmit($submit);
        echo $this->formHidden($form->get('id'));
        echo $this->form()->closeTag();
    ?>
</main>