<?php
$this->headTitle('Blog'); 
?>

<style>
  body {
    background-color: #2D2727;
    color: white;
  }
</style>

<h1>Listagem</h1>

<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($posts as $post):?>
        <tr>
            <td><?= $this->escapeHtml($post->id) ?></td> 
            <td><?= $this->escapeHtml($post->title) ?></td>
            <td><?= $this->escapeHtml($post->content) ?></td>
            <td>
              <a class="btn btn-outline-warning" href="#">Edit</a>
              <a class="btn btn-outline-danger" href="#">Delete</a>
            </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>



